import os, hashlib, hmac, secrets
from decimal import Decimal
from datetime import date
from fastapi import FastAPI, Form, Request
from fastapi.responses import HTMLResponse, RedirectResponse, StreamingResponse
from starlette.middleware.sessions import SessionMiddleware
from sqlalchemy import create_engine, text
from io import StringIO
import csv

DB_URL=os.getenv("DATABASE_URL","sqlite:///./accountant.db")
if DB_URL.startswith("postgresql://"): DB_URL=DB_URL.replace("postgresql://","postgresql+psycopg://",1)
engine=create_engine(DB_URL,pool_pre_ping=True)
app=FastAPI(title="Accountant Pro")
app.add_middleware(SessionMiddleware,secret_key=os.getenv("SESSION_SECRET","accountant-demo-secret-change-me"),same_site="lax",https_only=False)

def is_pg(): return DB_URL.startswith("postgresql")
def ident(sqlite_sql, pg_sql): return pg_sql if is_pg() else sqlite_sql
def q(sql,p=None,one=False):
    with engine.connect() as c:
        r=c.execute(text(sql),p or {})
        if r.returns_rows:
            data=r.mappings().all()
            return (data[0] if data else None) if one else data
def execq(sql,p=None):
    with engine.begin() as c: c.execute(text(sql),p or {})
def money(v): return f"AED {Decimal(str(v or 0)):,.2f}"
def hash_pw(pw,salt=None):
    salt=salt or secrets.token_hex(16)
    dk=hashlib.pbkdf2_hmac("sha256",pw.encode(),salt.encode(),150000)
    return f"{salt}:{dk.hex()}"
def verify_pw(pw,stored):
    try:
        salt,digest=stored.split(":",1)
        return hmac.compare_digest(hash_pw(pw,salt).split(":",1)[1],digest)
    except: return False

def init_db():
    stmts=[
      ident("""CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Active')""",
            """CREATE TABLE IF NOT EXISTS users(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Active')"""),
      ident("""CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,account_type TEXT NOT NULL,balance NUMERIC NOT NULL DEFAULT 0)""",
            """CREATE TABLE IF NOT EXISTS accounts(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,account_type TEXT NOT NULL,balance NUMERIC(14,2) NOT NULL DEFAULT 0)"""),
      ident("""CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT,phone TEXT,tax_number TEXT,address TEXT,balance NUMERIC NOT NULL DEFAULT 0)""",
            """CREATE TABLE IF NOT EXISTS customers(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL,email TEXT,phone TEXT,tax_number TEXT,address TEXT,balance NUMERIC(14,2) NOT NULL DEFAULT 0)"""),
      ident("""CREATE TABLE IF NOT EXISTS vendors(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT,phone TEXT,tax_number TEXT,address TEXT,balance NUMERIC NOT NULL DEFAULT 0)""",
            """CREATE TABLE IF NOT EXISTS vendors(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL,email TEXT,phone TEXT,tax_number TEXT,address TEXT,balance NUMERIC(14,2) NOT NULL DEFAULT 0)"""),
      ident("""CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,txn_date TEXT NOT NULL,description TEXT NOT NULL,category TEXT NOT NULL,txn_type TEXT NOT NULL,amount NUMERIC NOT NULL,tax NUMERIC NOT NULL DEFAULT 0,reference TEXT,account_code TEXT)""",
            """CREATE TABLE IF NOT EXISTS transactions(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,txn_date DATE NOT NULL,description TEXT NOT NULL,category TEXT NOT NULL,txn_type TEXT NOT NULL,amount NUMERIC(14,2) NOT NULL,tax NUMERIC(14,2) NOT NULL DEFAULT 0,reference TEXT,account_code TEXT)"""),
      ident("""CREATE TABLE IF NOT EXISTS invoices(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_no TEXT UNIQUE NOT NULL,customer_name TEXT NOT NULL,issue_date TEXT NOT NULL,due_date TEXT NOT NULL,status TEXT NOT NULL,subtotal NUMERIC NOT NULL,tax NUMERIC NOT NULL,total NUMERIC NOT NULL,paid NUMERIC NOT NULL DEFAULT 0,notes TEXT)""",
            """CREATE TABLE IF NOT EXISTS invoices(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,invoice_no TEXT UNIQUE NOT NULL,customer_name TEXT NOT NULL,issue_date DATE NOT NULL,due_date DATE NOT NULL,status TEXT NOT NULL,subtotal NUMERIC(14,2) NOT NULL,tax NUMERIC(14,2) NOT NULL,total NUMERIC(14,2) NOT NULL,paid NUMERIC(14,2) NOT NULL DEFAULT 0,notes TEXT)"""),
      ident("""CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,expense_date TEXT NOT NULL,vendor TEXT,category TEXT NOT NULL,description TEXT NOT NULL,subtotal NUMERIC NOT NULL,tax NUMERIC NOT NULL,total NUMERIC NOT NULL,payment_method TEXT,status TEXT NOT NULL)""",
            """CREATE TABLE IF NOT EXISTS expenses(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,expense_date DATE NOT NULL,vendor TEXT,category TEXT NOT NULL,description TEXT NOT NULL,subtotal NUMERIC(14,2) NOT NULL,tax NUMERIC(14,2) NOT NULL,total NUMERIC(14,2) NOT NULL,payment_method TEXT,status TEXT NOT NULL)"""),
      ident("""CREATE TABLE IF NOT EXISTS journal_entries(id INTEGER PRIMARY KEY AUTOINCREMENT,entry_date TEXT NOT NULL,reference TEXT,description TEXT NOT NULL,debit_account TEXT NOT NULL,credit_account TEXT NOT NULL,amount NUMERIC NOT NULL,status TEXT NOT NULL DEFAULT 'Posted')""",
            """CREATE TABLE IF NOT EXISTS journal_entries(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,entry_date DATE NOT NULL,reference TEXT,description TEXT NOT NULL,debit_account TEXT NOT NULL,credit_account TEXT NOT NULL,amount NUMERIC(14,2) NOT NULL,status TEXT NOT NULL DEFAULT 'Posted')""")
    ]
    for s in stmts: execq(s)
    if not q("SELECT id FROM users LIMIT 1"):
        execq("INSERT INTO users(name,email,password_hash,role,status) VALUES(:n,:e,:p,:r,'Active')",{"n":"System Admin","e":"admin@accountant.local","p":hash_pw("Admin123!"),"r":"Admin"})
        execq("INSERT INTO users(name,email,password_hash,role,status) VALUES(:n,:e,:p,:r,'Active')",{"n":"Accountant User","e":"accountant@accountant.local","p":hash_pw("Accountant123!"),"r":"Accountant"})
    if not q("SELECT id FROM accounts LIMIT 1"):
        for c,n,t,b in [("1000","Cash","Asset",28500),("1100","Accounts Receivable","Asset",14900),("2000","Accounts Payable","Liability",7200),("3000","Owner Equity","Equity",25000),("4000","Sales Revenue","Revenue",34800),("5000","Operating Expenses","Expense",7700)]:
            execq("INSERT INTO accounts(code,name,account_type,balance) VALUES(:c,:n,:t,:b)",{"c":c,"n":n,"t":t,"b":b})
    if not q("SELECT id FROM customers LIMIT 1"):
        for r in [("Acme Trading","accounts@acme.example","+971500000001","100001","Dubai, UAE"),("Northstar LLC","finance@northstar.example","+971500000002","100002","Sharjah, UAE"),("Blue Horizon","admin@bluehorizon.example","+971500000003","100003","Abu Dhabi, UAE")]:
            execq("INSERT INTO customers(name,email,phone,tax_number,address,balance) VALUES(:n,:e,:p,:t,:a,0)",{"n":r[0],"e":r[1],"p":r[2],"t":r[3],"a":r[4]})
    if not q("SELECT id FROM vendors LIMIT 1"):
        for r in [("Office Supplies Co","sales@office.example","+971520000001","200001","Dubai, UAE"),("Cloud Services FZ","billing@cloud.example","+971520000002","200002","Dubai, UAE")]:
            execq("INSERT INTO vendors(name,email,phone,tax_number,address,balance) VALUES(:n,:e,:p,:t,:a,0)",{"n":r[0],"e":r[1],"p":r[2],"t":r[3],"a":r[4]})
    if not q("SELECT id FROM transactions LIMIT 1"):
        for r in [("2026-09-30","Consulting revenue","Sales","income",25000,1250,"REV-001","4000"),("2026-09-30","Office rent","Operations","expense",6500,325,"EXP-001","5000"),("2026-09-30","Software subscriptions","IT","expense",1200,60,"EXP-002","5000"),("2026-09-30","Support contract","Services","income",9800,490,"REV-002","4000")]:
            execq("INSERT INTO transactions(txn_date,description,category,txn_type,amount,tax,reference,account_code) VALUES(:d,:x,:c,:t,:a,:v,:r,:ac)",{"d":r[0],"x":r[1],"c":r[2],"t":r[3],"a":r[4],"v":r[5],"r":r[6],"ac":r[7]})
    if not q("SELECT id FROM invoices LIMIT 1"):
        for r in [("INV-0001","Acme Trading","2026-09-30","2026-10-15","Paid",11428.57,571.43,12000,12000,"Paid in full"),("INV-0002","Northstar LLC","2026-09-30","2026-10-20","Unpaid",8095.24,404.76,8500,0,""),("INV-0003","Blue Horizon","2026-09-30","2026-10-25","Partially Paid",6095.24,304.76,6400,2000,"")]:
            execq("INSERT INTO invoices(invoice_no,customer_name,issue_date,due_date,status,subtotal,tax,total,paid,notes) VALUES(:i,:c,:is,:d,:s,:sub,:tax,:tot,:p,:n)",{"i":r[0],"c":r[1],"is":r[2],"d":r[3],"s":r[4],"sub":r[5],"tax":r[6],"tot":r[7],"p":r[8],"n":r[9]})
    if not q("SELECT id FROM expenses LIMIT 1"):
        execq("INSERT INTO expenses(expense_date,vendor,category,description,subtotal,tax,total,payment_method,status) VALUES('2026-09-30','Office Supplies Co','Office','Monthly office supplies',800,40,840,'Card','Paid')")
    if not q("SELECT id FROM journal_entries LIMIT 1"):
        execq("INSERT INTO journal_entries(entry_date,reference,description,debit_account,credit_account,amount,status) VALUES('2026-09-30','JE-001','Initial capital','1000 Cash','3000 Owner Equity',25000,'Posted')")

@app.on_event("startup")
def startup(): init_db()

def user(request): return request.session.get("user")
def guard(request):
    if not user(request): return RedirectResponse("/login",303)
def nav(role):
    links=[("Dashboard","/"),("Transactions","/transactions"),("Invoices","/invoices"),("Expenses","/expenses"),("Customers","/customers"),("Vendors","/vendors"),("Chart of Accounts","/accounts"),("Journal","/journal"),("Reports","/reports")]
    if role=="Admin": links.append(("Users","/users"))
    return "".join(f"<a href='{u}'>{n}</a>" for n,u in links)

def page(request,title,body):
    u=user(request)
    role=u["role"] if u else ""
    return f"""<!doctype html><html lang='en' dir='ltr'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{title} - Accountant Pro</title>
<style>
:root{{--bg:#f4f7fb;--ink:#14213d;--muted:#6b7280;--nav:#0d2742;--line:#dfe7ef;--brand:#1f6fb2;--good:#12805c;--bad:#c23b3b;--warn:#b7791f}}
*{{box-sizing:border-box}}body{{margin:0;font-family:Inter,"Segoe UI",Tahoma,Arial,sans-serif;background:var(--bg);color:var(--ink);text-align:start}}header{{background:var(--nav);color:#fff;padding:16px 24px;display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;z-index:5;gap:16px}}header b{{font-size:20px;white-space:nowrap}}.head-actions{{display:flex;align-items:center;gap:10px;flex-wrap:wrap;justify-content:flex-end}}.lang-switch{{background:#fff;color:#0d2742;border:0;border-radius:999px;padding:8px 13px;font-weight:700;cursor:pointer;min-width:72px}}.layout{{display:grid;grid-template-columns:240px minmax(0,1fr);min-height:calc(100vh - 58px)}}aside{{background:#fff;border-inline-end:1px solid var(--line);padding:18px}}aside a{{display:block;padding:10px 12px;margin:4px 0;border-radius:8px;color:#334155;text-decoration:none;text-align:start}}aside a:hover{{background:#eef5fb;color:var(--brand)}}main{{padding:26px;max-width:1400px;width:100%;margin:0 auto;min-width:0}}.top{{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}}.top h1{{margin:0}}.grid{{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}}.card{{background:#fff;border:1px solid var(--line);border-radius:14px;padding:18px;box-shadow:0 3px 12px rgba(15,23,42,.04);overflow:auto}}.kpi{{font-size:26px;font-weight:750;margin-top:7px;direction:ltr;unicode-bidi:isolate;text-align:start}}.muted{{color:var(--muted);font-size:13px}}.good{{color:var(--good)}}.bad{{color:var(--bad)}}.warn{{color:var(--warn)}}table{{width:100%;border-collapse:collapse;background:#fff;min-width:680px}}th,td{{padding:11px 12px;border-bottom:1px solid var(--line);text-align:start;font-size:14px;vertical-align:middle}}th{{background:#eff4f8;white-space:nowrap}}form.gridform{{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr));gap:10px;margin-bottom:16px}}input,select,textarea,button{{padding:10px 11px;border:1px solid #cbd5e1;border-radius:8px;font:inherit;text-align:start}}input[type="email"],input[type="password"],input[type="number"],input[type="date"]{{direction:ltr}}button,.btn{{background:var(--brand);color:white;border:0;text-decoration:none;display:inline-block;padding:10px 14px;border-radius:8px;cursor:pointer;text-align:center}}.tag{{padding:4px 8px;border-radius:999px;background:#edf2f7;font-size:12px;white-space:nowrap}}.section{{margin-top:20px}}.login{{max-width:440px;margin:70px auto}}.login input{{width:100%;margin:8px 0}}.login button{{width:100%;margin-top:8px}}.ltr{{direction:ltr;unicode-bidi:isolate}}html[dir="rtl"] body{{font-family:Tahoma,"Segoe UI",Arial,sans-serif}}html[dir="rtl"] .head-actions{{justify-content:flex-start}}html[dir="rtl"] .layout{{grid-template-columns:240px minmax(0,1fr)}}html[dir="rtl"] input:not([type="email"]):not([type="password"]):not([type="number"]):not([type="date"]),html[dir="rtl"] select,html[dir="rtl"] textarea{{direction:rtl;text-align:right}}html[dir="rtl"] table,html[dir="rtl"] th,html[dir="rtl"] td{{text-align:right}}html[dir="rtl"] aside a{{text-align:right}}html[dir="rtl"] .kpi{{text-align:right}}html[dir="rtl"] .login{{text-align:right}}
@media(max-width:1050px){{form.gridform{{grid-template-columns:repeat(3,minmax(140px,1fr))}}.grid{{grid-template-columns:repeat(2,minmax(0,1fr))}}}}
@media(max-width:760px){{header{{padding:13px 14px}}.layout{{grid-template-columns:1fr}}aside{{display:none}}.grid{{grid-template-columns:1fr}}form.gridform{{grid-template-columns:1fr}}main{{padding:14px}}.card{{padding:14px}}.head-actions{{font-size:13px}}}}
</style></head><body>
<header><b data-i18n='app_name'>Accountant Pro</b><div class='head-actions'><button class='lang-switch' type='button' onclick='toggleLanguage()'>العربية</button><span>{u['name'] if u else ''} {f"· {role}" if u else ''}</span>{f"<a data-i18n='logout' style='color:#fff' href='/logout'>Logout</a>" if u else ''}</div></header>
{f"<div class='layout'><aside>{nav(role)}</aside><main><div class='top'><h1>{title}</h1></div>{body}</main></div>" if u else f"<main>{body}</main>"}
<script>
const AR = {{
"Accountant Pro":"المحاسب برو","Dashboard":"لوحة التحكم","Transactions":"المعاملات","Invoices":"الفواتير","Expenses":"المصروفات","Customers":"العملاء","Vendors":"الموردون","Chart of Accounts":"دليل الحسابات","Journal":"القيود اليومية","Journal Entries":"القيود اليومية","Reports":"التقارير","Users":"المستخدمون","Users & Roles":"المستخدمون والصلاحيات","Logout":"تسجيل الخروج",
"Login":"تسجيل الدخول","Sign in":"تسجيل الدخول","Use one of the demo accounts below.":"استخدم أحد الحسابات التجريبية أدناه.","Email":"البريد الإلكتروني","Password":"كلمة المرور","Admin:":"المدير:","Accountant:":"المحاسب:",
"Revenue":"الإيرادات","Expenses":"المصروفات","Net profit":"صافي الربح","VAT tracked":"ضريبة القيمة المضافة","Accounts receivable":"الذمم المدينة","Accounts payable":"الذمم الدائنة","Overdue invoices":"الفواتير المتأخرة","Database":"قاعدة البيانات","SQLite Demo":"SQLite تجريبي","Recent activity":"النشاط الأخير",
"Date":"التاريخ","Description":"الوصف","Category":"الفئة","Type":"النوع","Amount":"المبلغ","Reference":"المرجع","Ref":"المرجع","Account code":"رمز الحساب","VAT":"ضريبة القيمة المضافة","Income":"إيراد","Expense":"مصروف","income":"إيراد","expense":"مصروف","Add transaction":"إضافة معاملة",
"Name":"الاسم","Customer name":"اسم العميل","Vendor name":"اسم المورد","Phone":"الهاتف","TRN / Tax no.":"الرقم الضريبي","Tax no.":"الرقم الضريبي","Address":"العنوان","Balance":"الرصيد","Add customer":"إضافة عميل","Add vendor":"إضافة مورد",
"Invoice no.":"رقم الفاتورة","Invoice":"الفاتورة","Customer":"العميل","Issue":"الإصدار","Due":"الاستحقاق","Status":"الحالة","Subtotal":"المجموع قبل الضريبة","Total":"الإجمالي","Paid":"مدفوع","Unpaid":"غير مدفوع","Partially Paid":"مدفوع جزئياً","Notes":"ملاحظات","Create invoice":"إنشاء فاتورة",
"Vendor":"المورد","Payment method":"طريقة الدفع","Bank Transfer":"تحويل بنكي","Card":"بطاقة","Cash":"نقداً","Add expense":"إضافة مصروف",
"Code":"الرمز","Account":"الحساب","Account name":"اسم الحساب","Asset":"أصل","Liability":"التزام","Equity":"حقوق الملكية","Revenue":"الإيرادات","Expense":"مصروف","Add account":"إضافة حساب",
"Debit":"مدين","Credit":"دائن","Debit account":"الحساب المدين","Credit account":"الحساب الدائن","Post entry":"ترحيل القيد","Posted":"مرحل",
"Profit & Loss":"الأرباح والخسائر","Balance Sheet Snapshot":"ملخص الميزانية العمومية","Assets":"الأصول","Liabilities":"الالتزامات","Equity":"حقوق الملكية","VAT Summary":"ملخص ضريبة القيمة المضافة","Output VAT":"ضريبة المخرجات","Input VAT":"ضريبة المدخلات","Net VAT":"صافي الضريبة","Exports":"التصدير","Transactions CSV":"تصدير المعاملات CSV","Invoices CSV":"تصدير الفواتير CSV",
"Full name":"الاسم الكامل","Role":"الدور","Admin":"مدير","Accountant":"محاسب","Viewer":"مشاهد","Active":"نشط","Add user":"إضافة مستخدم",
"Consulting revenue":"إيراد الاستشارات","Sales":"المبيعات","Office rent":"إيجار المكتب","Operations":"العمليات","Software subscriptions":"اشتراكات البرامج","IT":"تقنية المعلومات","Support contract":"عقد الدعم","Services":"الخدمات","Office":"المكتب","Monthly office supplies":"مستلزمات المكتب الشهرية","Initial capital":"رأس المال الافتتاحي","Paid in full":"مدفوع بالكامل","System Admin":"مدير النظام","Accountant User":"مستخدم محاسب",
"Cash":"النقد","Accounts Receivable":"الذمم المدينة","Accounts Payable":"الذمم الدائنة","Owner Equity":"حقوق المالك","Sales Revenue":"إيرادات المبيعات","Operating Expenses":"المصروفات التشغيلية"
}};
function translateText(s,lang) {{
  const trimmed=s.trim();
  if(!trimmed) return s;
  if(lang==='ar' && AR[trimmed]) return s.replace(trimmed,AR[trimmed]);
  if(lang==='en') {{
    const pair=Object.entries(AR).find(([en,ar])=>ar===trimmed);
    if(pair) return s.replace(trimmed,pair[0]);
  }}
  return s;
}}
function applyLanguage(lang) {{
  document.documentElement.lang=lang;
  document.documentElement.dir=lang==='ar'?'rtl':'ltr';
  localStorage.setItem('accountant_lang',lang);
  document.querySelectorAll('body *').forEach(el=>{{
    if(['SCRIPT','STYLE','INPUT','TEXTAREA'].includes(el.tagName)) return;
    [...el.childNodes].forEach(n=>{{if(n.nodeType===3)n.nodeValue=translateText(n.nodeValue,lang);}});
  }});
  document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(el=>{{
    const p=el.getAttribute('placeholder');
    if(lang==='ar' && AR[p]) el.setAttribute('placeholder',AR[p]);
    else if(lang==='en') {{
      const pair=Object.entries(AR).find(([en,ar])=>ar===p);
      if(pair) el.setAttribute('placeholder',pair[0]);
    }}
  }});
  document.querySelectorAll('option').forEach(el=>{{el.textContent=translateText(el.textContent,lang);}});
  document.querySelector('.lang-switch').textContent=lang==='ar'?'English':'العربية';
  document.title=(lang==='ar'?(AR['{title}']||'{title}'):'{title}')+' - '+(lang==='ar'?'المحاسب برو':'Accountant Pro');
}}
function toggleLanguage() {{
  const current=localStorage.getItem('accountant_lang')||'en';
  applyLanguage(current==='ar'?'en':'ar');
}}
applyLanguage(localStorage.getItem('accountant_lang')||'en');
</script>
</body></html>"""

@app.get("/login",response_class=HTMLResponse)
def login_get(request:Request):
    if user(request): return RedirectResponse("/",303)
    return page(request,"Login","""<div class='login card'><h2>Sign in</h2><p class='muted'>Use one of the demo accounts below.</p><form method='post'><input name='email' type='email' placeholder='Email' required><input name='password' type='password' placeholder='Password' required><button>Sign in</button></form><hr><p><b>Admin:</b> admin@accountant.local / Admin123!</p><p><b>Accountant:</b> accountant@accountant.local / Accountant123!</p></div>""")

@app.post("/login")
def login_post(request:Request,email:str=Form(...),password:str=Form(...)):
    r=q("SELECT * FROM users WHERE email=:e AND status='Active'",{"e":email},True)
    if not r or not verify_pw(password,r["password_hash"]): return RedirectResponse("/login?error=1",303)
    request.session["user"]={"id":r["id"],"name":r["name"],"email":r["email"],"role":r["role"]}
    return RedirectResponse("/",303)

@app.get("/logout")
def logout(request:Request):
    request.session.clear(); return RedirectResponse("/login",303)

@app.get("/health")
def health(): return {"status":"ok","database":"postgresql" if is_pg() else "sqlite"}

@app.get("/",response_class=HTMLResponse)
def dashboard(request:Request):
    g=guard(request)
    if g:return g
    s=q("""SELECT COALESCE(SUM(CASE WHEN txn_type='income' THEN amount ELSE 0 END),0) income,
    COALESCE(SUM(CASE WHEN txn_type='expense' THEN amount ELSE 0 END),0) expense,
    COALESCE(SUM(tax),0) tax FROM transactions""",one=True)
    ar=q("SELECT COALESCE(SUM(total-paid),0) v FROM invoices WHERE status!='Paid'",one=True)["v"]
    ap=q("SELECT COALESCE(SUM(total),0) v FROM expenses WHERE status!='Paid'",one=True)["v"]
    overdue=q("SELECT COUNT(*) c FROM invoices WHERE due_date < :d AND status!='Paid'",{"d":str(date.today())},True)["c"]
    recent=q("SELECT * FROM transactions ORDER BY id DESC LIMIT 6")
    rows="".join(f"<tr><td>{r['txn_date']}</td><td>{r['description']}</td><td>{r['category']}</td><td>{r['txn_type']}</td><td>{money(r['amount'])}</td></tr>" for r in recent)
    profit=Decimal(str(s["income"]))-Decimal(str(s["expense"]))
    body=f"""<div class='grid'>
    <div class='card'><div class='muted'>Revenue</div><div class='kpi good'>{money(s['income'])}</div></div>
    <div class='card'><div class='muted'>Expenses</div><div class='kpi bad'>{money(s['expense'])}</div></div>
    <div class='card'><div class='muted'>Net profit</div><div class='kpi'>{money(profit)}</div></div>
    <div class='card'><div class='muted'>VAT tracked</div><div class='kpi'>{money(s['tax'])}</div></div></div>
    <div class='grid section'><div class='card'><div class='muted'>Accounts receivable</div><div class='kpi'>{money(ar)}</div></div><div class='card'><div class='muted'>Accounts payable</div><div class='kpi'>{money(ap)}</div></div><div class='card'><div class='muted'>Overdue invoices</div><div class='kpi warn'>{overdue}</div></div><div class='card'><div class='muted'>Database</div><div class='kpi'>{'PostgreSQL' if is_pg() else 'SQLite Demo'}</div></div></div>
    <div class='card section'><h3>Recent activity</h3><table><tr><th>Date</th><th>Description</th><th>Category</th><th>Type</th><th>Amount</th></tr>{rows}</table></div>"""
    return page(request,"Dashboard",body)

@app.get("/transactions",response_class=HTMLResponse)
def transactions(request:Request):
    g=guard(request)
    if g:return g
    items=q("SELECT * FROM transactions ORDER BY id DESC")
    rows="".join(f"<tr><td>{r['txn_date']}</td><td>{r['reference'] or ''}</td><td>{r['description']}</td><td>{r['category']}</td><td>{r['txn_type']}</td><td>{money(r['amount'])}</td><td>{money(r['tax'])}</td></tr>" for r in items)
    form="""<form class='gridform' method='post'><input name='txn_date' type='date' required><input name='reference' placeholder='Reference'><input name='description' placeholder='Description' required><input name='category' placeholder='Category' required><select name='txn_type'><option value='income'>Income</option><option value='expense'>Expense</option></select><input name='account_code' placeholder='Account code'><input name='amount' type='number' step='0.01' placeholder='Amount' required><input name='tax' type='number' step='0.01' placeholder='VAT' value='0'><button>Add transaction</button></form>"""
    return page(request,"Transactions",f"<div class='card'>{form}<table><tr><th>Date</th><th>Ref</th><th>Description</th><th>Category</th><th>Type</th><th>Amount</th><th>VAT</th></tr>{rows}</table></div>")

@app.post("/transactions")
def add_transaction(request:Request,txn_date:str=Form(...),reference:str=Form(""),description:str=Form(...),category:str=Form(...),txn_type:str=Form(...),account_code:str=Form(""),amount:Decimal=Form(...),tax:Decimal=Form(0)):
    if not user(request):return RedirectResponse("/login",303)
    execq("INSERT INTO transactions(txn_date,description,category,txn_type,amount,tax,reference,account_code) VALUES(:d,:x,:c,:t,:a,:v,:r,:ac)",{"d":txn_date,"x":description,"c":category,"t":txn_type,"a":amount,"v":tax,"r":reference,"ac":account_code})
    return RedirectResponse("/transactions",303)

@app.get("/customers",response_class=HTMLResponse)
def customers(request:Request):
    g=guard(request)
    if g:return g
    items=q("SELECT * FROM customers ORDER BY id DESC")
    rows="".join(f"<tr><td>{r['name']}</td><td>{r['email'] or ''}</td><td>{r['phone'] or ''}</td><td>{r['tax_number'] or ''}</td><td>{money(r['balance'])}</td></tr>" for r in items)
    form="""<form class='gridform' method='post'><input name='name' placeholder='Customer name' required><input name='email' type='email' placeholder='Email'><input name='phone' placeholder='Phone'><input name='tax_number' placeholder='TRN / Tax no.'><input name='address' placeholder='Address'><button>Add customer</button></form>"""
    return page(request,"Customers",f"<div class='card'>{form}<table><tr><th>Name</th><th>Email</th><th>Phone</th><th>Tax no.</th><th>Balance</th></tr>{rows}</table></div>")

@app.post("/customers")
def add_customer(request:Request,name:str=Form(...),email:str=Form(""),phone:str=Form(""),tax_number:str=Form(""),address:str=Form("")):
    if not user(request):return RedirectResponse("/login",303)
    execq("INSERT INTO customers(name,email,phone,tax_number,address,balance) VALUES(:n,:e,:p,:t,:a,0)",{"n":name,"e":email,"p":phone,"t":tax_number,"a":address})
    return RedirectResponse("/customers",303)

@app.get("/vendors",response_class=HTMLResponse)
def vendors(request:Request):
    g=guard(request)
    if g:return g
    items=q("SELECT * FROM vendors ORDER BY id DESC")
    rows="".join(f"<tr><td>{r['name']}</td><td>{r['email'] or ''}</td><td>{r['phone'] or ''}</td><td>{r['tax_number'] or ''}</td><td>{money(r['balance'])}</td></tr>" for r in items)
    form="""<form class='gridform' method='post'><input name='name' placeholder='Vendor name' required><input name='email' type='email' placeholder='Email'><input name='phone' placeholder='Phone'><input name='tax_number' placeholder='TRN / Tax no.'><input name='address' placeholder='Address'><button>Add vendor</button></form>"""
    return page(request,"Vendors",f"<div class='card'>{form}<table><tr><th>Name</th><th>Email</th><th>Phone</th><th>Tax no.</th><th>Balance</th></tr>{rows}</table></div>")

@app.post("/vendors")
def add_vendor(request:Request,name:str=Form(...),email:str=Form(""),phone:str=Form(""),tax_number:str=Form(""),address:str=Form("")):
    if not user(request):return RedirectResponse("/login",303)
    execq("INSERT INTO vendors(name,email,phone,tax_number,address,balance) VALUES(:n,:e,:p,:t,:a,0)",{"n":name,"e":email,"p":phone,"t":tax_number,"a":address})
    return RedirectResponse("/vendors",303)

@app.get("/invoices",response_class=HTMLResponse)
def invoices(request:Request):
    g=guard(request)
    if g:return g
    items=q("SELECT * FROM invoices ORDER BY id DESC")
    rows="".join(f"<tr><td>{r['invoice_no']}</td><td>{r['customer_name']}</td><td>{r['issue_date']}</td><td>{r['due_date']}</td><td><span class='tag'>{r['status']}</span></td><td>{money(r['total'])}</td><td>{money(r['paid'])}</td><td>{money(Decimal(str(r['total']))-Decimal(str(r['paid'])))}</td></tr>" for r in items)
    form="""<form class='gridform' method='post'><input name='invoice_no' placeholder='Invoice no.' required><input name='customer_name' placeholder='Customer' required><input name='issue_date' type='date' required><input name='due_date' type='date' required><input name='subtotal' type='number' step='0.01' placeholder='Subtotal' required><input name='tax' type='number' step='0.01' placeholder='VAT' value='0'><input name='paid' type='number' step='0.01' placeholder='Paid' value='0'><input name='notes' placeholder='Notes'><button>Create invoice</button></form>"""
    return page(request,"Invoices",f"<div class='card'>{form}<table><tr><th>Invoice</th><th>Customer</th><th>Issue</th><th>Due</th><th>Status</th><th>Total</th><th>Paid</th><th>Balance</th></tr>{rows}</table></div>")

@app.post("/invoices")
def add_invoice(request:Request,invoice_no:str=Form(...),customer_name:str=Form(...),issue_date:str=Form(...),due_date:str=Form(...),subtotal:Decimal=Form(...),tax:Decimal=Form(0),paid:Decimal=Form(0),notes:str=Form("")):
    if not user(request):return RedirectResponse("/login",303)
    total=subtotal+tax
    status="Paid" if paid>=total else ("Partially Paid" if paid>0 else "Unpaid")
    execq("INSERT INTO invoices(invoice_no,customer_name,issue_date,due_date,status,subtotal,tax,total,paid,notes) VALUES(:i,:c,:is,:d,:s,:sub,:tax,:tot,:p,:n)",{"i":invoice_no,"c":customer_name,"is":issue_date,"d":due_date,"s":status,"sub":subtotal,"tax":tax,"tot":total,"p":paid,"n":notes})
    return RedirectResponse("/invoices",303)

@app.get("/expenses",response_class=HTMLResponse)
def expenses(request:Request):
    g=guard(request)
    if g:return g
    items=q("SELECT * FROM expenses ORDER BY id DESC")
    rows="".join(f"<tr><td>{r['expense_date']}</td><td>{r['vendor'] or ''}</td><td>{r['category']}</td><td>{r['description']}</td><td>{money(r['subtotal'])}</td><td>{money(r['tax'])}</td><td>{money(r['total'])}</td><td>{r['status']}</td></tr>" for r in items)
    form="""<form class='gridform' method='post'><input name='expense_date' type='date' required><input name='vendor' placeholder='Vendor'><input name='category' placeholder='Category' required><input name='description' placeholder='Description' required><input name='subtotal' type='number' step='0.01' placeholder='Subtotal' required><input name='tax' type='number' step='0.01' placeholder='VAT' value='0'><select name='payment_method'><option>Bank Transfer</option><option>Card</option><option>Cash</option></select><select name='status'><option>Paid</option><option>Unpaid</option></select><button>Add expense</button></form>"""
    return page(request,"Expenses",f"<div class='card'>{form}<table><tr><th>Date</th><th>Vendor</th><th>Category</th><th>Description</th><th>Subtotal</th><th>VAT</th><th>Total</th><th>Status</th></tr>{rows}</table></div>")

@app.post("/expenses")
def add_expense(request:Request,expense_date:str=Form(...),vendor:str=Form(""),category:str=Form(...),description:str=Form(...),subtotal:Decimal=Form(...),tax:Decimal=Form(0),payment_method:str=Form(...),status:str=Form(...)):
    if not user(request):return RedirectResponse("/login",303)
    execq("INSERT INTO expenses(expense_date,vendor,category,description,subtotal,tax,total,payment_method,status) VALUES(:d,:v,:c,:x,:s,:t,:tot,:pm,:st)",{"d":expense_date,"v":vendor,"c":category,"x":description,"s":subtotal,"t":tax,"tot":subtotal+tax,"pm":payment_method,"st":status})
    return RedirectResponse("/expenses",303)

@app.get("/accounts",response_class=HTMLResponse)
def accounts(request:Request):
    g=guard(request)
    if g:return g
    items=q("SELECT * FROM accounts ORDER BY code")
    rows="".join(f"<tr><td>{r['code']}</td><td>{r['name']}</td><td>{r['account_type']}</td><td>{money(r['balance'])}</td></tr>" for r in items)
    form="""<form class='gridform' method='post'><input name='code' placeholder='Code' required><input name='name' placeholder='Account name' required><select name='account_type'><option>Asset</option><option>Liability</option><option>Equity</option><option>Revenue</option><option>Expense</option></select><input name='balance' type='number' step='0.01' value='0'><button>Add account</button></form>"""
    return page(request,"Chart of Accounts",f"<div class='card'>{form}<table><tr><th>Code</th><th>Account</th><th>Type</th><th>Balance</th></tr>{rows}</table></div>")

@app.post("/accounts")
def add_account(request:Request,code:str=Form(...),name:str=Form(...),account_type:str=Form(...),balance:Decimal=Form(0)):
    if not user(request):return RedirectResponse("/login",303)
    execq("INSERT INTO accounts(code,name,account_type,balance) VALUES(:c,:n,:t,:b)",{"c":code,"n":name,"t":account_type,"b":balance})
    return RedirectResponse("/accounts",303)

@app.get("/journal",response_class=HTMLResponse)
def journal(request:Request):
    g=guard(request)
    if g:return g
    items=q("SELECT * FROM journal_entries ORDER BY id DESC")
    rows="".join(f"<tr><td>{r['entry_date']}</td><td>{r['reference'] or ''}</td><td>{r['description']}</td><td>{r['debit_account']}</td><td>{r['credit_account']}</td><td>{money(r['amount'])}</td><td>{r['status']}</td></tr>" for r in items)
    form="""<form class='gridform' method='post'><input name='entry_date' type='date' required><input name='reference' placeholder='Reference'><input name='description' placeholder='Description' required><input name='debit_account' placeholder='Debit account' required><input name='credit_account' placeholder='Credit account' required><input name='amount' type='number' step='0.01' required><button>Post entry</button></form>"""
    return page(request,"Journal Entries",f"<div class='card'>{form}<table><tr><th>Date</th><th>Reference</th><th>Description</th><th>Debit</th><th>Credit</th><th>Amount</th><th>Status</th></tr>{rows}</table></div>")

@app.post("/journal")
def add_journal(request:Request,entry_date:str=Form(...),reference:str=Form(""),description:str=Form(...),debit_account:str=Form(...),credit_account:str=Form(...),amount:Decimal=Form(...)):
    if not user(request):return RedirectResponse("/login",303)
    execq("INSERT INTO journal_entries(entry_date,reference,description,debit_account,credit_account,amount,status) VALUES(:d,:r,:x,:db,:cr,:a,'Posted')",{"d":entry_date,"r":reference,"x":description,"db":debit_account,"cr":credit_account,"a":amount})
    return RedirectResponse("/journal",303)

@app.get("/reports",response_class=HTMLResponse)
def reports(request:Request):
    g=guard(request)
    if g:return g
    pl=q("""SELECT COALESCE(SUM(CASE WHEN txn_type='income' THEN amount ELSE 0 END),0) revenue,
    COALESCE(SUM(CASE WHEN txn_type='expense' THEN amount ELSE 0 END),0) expenses FROM transactions""",one=True)
    assets=sum(Decimal(str(r["balance"])) for r in q("SELECT balance FROM accounts WHERE account_type='Asset'"))
    liabilities=sum(Decimal(str(r["balance"])) for r in q("SELECT balance FROM accounts WHERE account_type='Liability'"))
    equity=sum(Decimal(str(r["balance"])) for r in q("SELECT balance FROM accounts WHERE account_type='Equity'"))
    salesvat=q("SELECT COALESCE(SUM(tax),0) v FROM invoices",one=True)["v"]
    expvat=q("SELECT COALESCE(SUM(tax),0) v FROM expenses",one=True)["v"]
    netvat=Decimal(str(salesvat))-Decimal(str(expvat))
    body=f"""<div class='grid'><div class='card'><h3>Profit & Loss</h3><p>Revenue: <b>{money(pl['revenue'])}</b></p><p>Expenses: <b>{money(pl['expenses'])}</b></p><p>Net profit: <b>{money(Decimal(str(pl['revenue']))-Decimal(str(pl['expenses'])))}</b></p></div>
    <div class='card'><h3>Balance Sheet Snapshot</h3><p>Assets: <b>{money(assets)}</b></p><p>Liabilities: <b>{money(liabilities)}</b></p><p>Equity: <b>{money(equity)}</b></p></div>
    <div class='card'><h3>VAT Summary</h3><p>Output VAT: <b>{money(salesvat)}</b></p><p>Input VAT: <b>{money(expvat)}</b></p><p>Net VAT: <b>{money(netvat)}</b></p></div>
    <div class='card'><h3>Exports</h3><p><a class='btn' href='/export/transactions.csv'>Transactions CSV</a></p><p><a class='btn' href='/export/invoices.csv'>Invoices CSV</a></p></div></div>"""
    return page(request,"Reports",body)

@app.get("/users",response_class=HTMLResponse)
def users_page(request:Request):
    g=guard(request)
    if g:return g
    if user(request)["role"]!="Admin": return RedirectResponse("/",303)
    items=q("SELECT id,name,email,role,status FROM users ORDER BY id")
    rows="".join(f"<tr><td>{r['name']}</td><td>{r['email']}</td><td>{r['role']}</td><td>{r['status']}</td></tr>" for r in items)
    form="""<form class='gridform' method='post'><input name='name' placeholder='Full name' required><input name='email' type='email' placeholder='Email' required><input name='password' type='password' placeholder='Password' required><select name='role'><option>Accountant</option><option>Admin</option><option>Viewer</option></select><button>Add user</button></form>"""
    return page(request,"Users & Roles",f"<div class='card'>{form}<table><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th></tr>{rows}</table></div>")

@app.post("/users")
def add_user(request:Request,name:str=Form(...),email:str=Form(...),password:str=Form(...),role:str=Form(...)):
    if not user(request) or user(request)["role"]!="Admin":return RedirectResponse("/",303)
    execq("INSERT INTO users(name,email,password_hash,role,status) VALUES(:n,:e,:p,:r,'Active')",{"n":name,"e":email,"p":hash_pw(password),"r":role})
    return RedirectResponse("/users",303)

@app.get("/export/{kind}.csv")
def export_csv(request:Request,kind:str):
    if not user(request):return RedirectResponse("/login",303)
    if kind=="transactions":
        rows=q("SELECT txn_date,reference,description,category,txn_type,amount,tax,account_code FROM transactions ORDER BY id")
    elif kind=="invoices":
        rows=q("SELECT invoice_no,customer_name,issue_date,due_date,status,subtotal,tax,total,paid FROM invoices ORDER BY id")
    else:
        return RedirectResponse("/reports",303)
    out=StringIO()
    if rows:
        w=csv.DictWriter(out,fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows([dict(r) for r in rows])
    return StreamingResponse(iter([out.getvalue()]),media_type="text/csv",headers={"Content-Disposition":f"attachment; filename={kind}.csv"})
