import os
from decimal import Decimal
from fastapi import FastAPI, Form
from fastapi.responses import HTMLResponse, RedirectResponse
from sqlalchemy import create_engine, text

url=os.getenv("DATABASE_URL","sqlite:///./accountant.db")
if url.startswith("postgresql://"): url=url.replace("postgresql://","postgresql+psycopg://",1)
engine=create_engine(url,pool_pre_ping=True)
app=FastAPI(title="Accountant MVP")

def init():
    with engine.begin() as c:
        c.execute(text("""CREATE TABLE IF NOT EXISTS transactions(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        txn_date DATE NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL,
        txn_type TEXT NOT NULL, amount NUMERIC(12,2) NOT NULL)""") if "postgresql" in url else text("""CREATE TABLE IF NOT EXISTS transactions(
        id INTEGER PRIMARY KEY AUTOINCREMENT, txn_date TEXT NOT NULL, description TEXT NOT NULL,
        category TEXT NOT NULL, txn_type TEXT NOT NULL, amount NUMERIC NOT NULL)"""))
        c.execute(text("""CREATE TABLE IF NOT EXISTS customers(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,name TEXT NOT NULL,email TEXT,phone TEXT)""") if "postgresql" in url else text("""CREATE TABLE IF NOT EXISTS customers(
        id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT,phone TEXT)"""))
        c.execute(text("""CREATE TABLE IF NOT EXISTS invoices(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,customer_name TEXT NOT NULL,
        issue_date DATE NOT NULL,due_date DATE NOT NULL,status TEXT NOT NULL,amount NUMERIC(12,2) NOT NULL)""") if "postgresql" in url else text("""CREATE TABLE IF NOT EXISTS invoices(
        id INTEGER PRIMARY KEY AUTOINCREMENT,customer_name TEXT NOT NULL,issue_date TEXT NOT NULL,
        due_date TEXT NOT NULL,status TEXT NOT NULL,amount NUMERIC NOT NULL)"""))
        if c.execute(text("SELECT COUNT(*) FROM transactions")).scalar()==0:
            for r in [("2026-09-30","Consulting revenue","Sales","income",25000),("2026-09-30","Office rent","Operations","expense",6500),("2026-09-30","Software subscriptions","IT","expense",1200),("2026-09-30","Support contract","Services","income",9800)]:
                c.execute(text("INSERT INTO transactions(txn_date,description,category,txn_type,amount) VALUES(:d,:x,:c,:t,:a)"),{"d":r[0],"x":r[1],"c":r[2],"t":r[3],"a":r[4]})
        if c.execute(text("SELECT COUNT(*) FROM customers")).scalar()==0:
            for r in [("Acme Trading","accounts@acme.example","+971 50 000 0001"),("Northstar LLC","finance@northstar.example","+971 50 000 0002"),("Blue Horizon","admin@bluehorizon.example","+971 50 000 0003")]:
                c.execute(text("INSERT INTO customers(name,email,phone) VALUES(:n,:e,:p)"),{"n":r[0],"e":r[1],"p":r[2]})
        if c.execute(text("SELECT COUNT(*) FROM invoices")).scalar()==0:
            for r in [("Acme Trading","2026-09-30","2026-10-15","Paid",12000),("Northstar LLC","2026-09-30","2026-10-20","Unpaid",8500),("Blue Horizon","2026-09-30","2026-10-25","Unpaid",6400)]:
                c.execute(text("INSERT INTO invoices(customer_name,issue_date,due_date,status,amount) VALUES(:c,:i,:d,:s,:a)"),{"c":r[0],"i":r[1],"d":r[2],"s":r[3],"a":r[4]})

@app.on_event("startup")
def startup(): init()

def m(v): return f"AED {Decimal(str(v or 0)):,.2f}"
def page(title,body):
    return f"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title>
<style>body{{margin:0;font-family:Arial;background:#f5f7fb;color:#172033}}header{{background:#102a43;color:white;padding:18px 28px;display:flex;justify-content:space-between}}nav a{{color:#dbeafe;margin-left:18px;text-decoration:none}}main{{max-width:1180px;margin:28px auto;padding:0 18px}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}}.card{{background:white;border:1px solid #e5e7eb;border-radius:14px;padding:18px;margin-bottom:20px}}.kpi{{font-size:26px;font-weight:700;margin-top:8px}}table{{width:100%;border-collapse:collapse}}th,td{{padding:12px;border-bottom:1px solid #e5e7eb;text-align:left}}th{{background:#eef3f8}}form{{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-bottom:18px}}input,select,button{{padding:10px;border:1px solid #ccd5df;border-radius:8px}}button{{background:#1f4e79;color:white;border:0}}@media(max-width:800px){{.grid{{grid-template-columns:1fr 1fr}}form{{grid-template-columns:1fr 1fr}}}}</style></head>
<body><header><b>Accountant MVP</b><nav><a href="/">Dashboard</a><a href="/transactions">Transactions</a><a href="/invoices">Invoices</a><a href="/customers">Customers</a></nav></header><main>{body}</main></body></html>"""

@app.get("/health")
def health(): return {"status":"ok"}

@app.get("/",response_class=HTMLResponse)
def home():
    with engine.connect() as c:
        s=c.execute(text("""SELECT COALESCE(SUM(CASE WHEN txn_type='income' THEN amount ELSE 0 END),0) income,
        COALESCE(SUM(CASE WHEN txn_type='expense' THEN amount ELSE 0 END),0) expense FROM transactions""")).mappings().one()
        unpaid=c.execute(text("SELECT COUNT(*) FROM invoices WHERE status='Unpaid'")).scalar()
        customers=c.execute(text("SELECT COUNT(*) FROM customers")).scalar()
        tx=c.execute(text("SELECT * FROM transactions ORDER BY id DESC LIMIT 6")).mappings().all()
    profit=Decimal(str(s["income"]))-Decimal(str(s["expense"]))
    rows="".join(f"<tr><td>{r['txn_date']}</td><td>{r['description']}</td><td>{r['category']}</td><td>{r['txn_type']}</td><td>{m(r['amount'])}</td></tr>" for r in tx)
    return page("Dashboard",f"<h1>Financial Dashboard</h1><div class='grid'><div class='card'>Income<div class='kpi'>{m(s['income'])}</div></div><div class='card'>Expenses<div class='kpi'>{m(s['expense'])}</div></div><div class='card'>Net Profit<div class='kpi'>{m(profit)}</div></div><div class='card'>Customers / Unpaid<div class='kpi'>{customers} / {unpaid}</div></div></div><div class='card'><h2>Recent transactions</h2><table><tr><th>Date</th><th>Description</th><th>Category</th><th>Type</th><th>Amount</th></tr>{rows}</table></div>")

@app.get("/transactions",response_class=HTMLResponse)
def txs():
    with engine.connect() as c: items=c.execute(text("SELECT * FROM transactions ORDER BY id DESC")).mappings().all()
    rows="".join(f"<tr><td>{r['txn_date']}</td><td>{r['description']}</td><td>{r['category']}</td><td>{r['txn_type']}</td><td>{m(r['amount'])}</td></tr>" for r in items)
    return page("Transactions",f"""<h1>Transactions</h1><div class='card'><form method='post'><input name='txn_date' type='date' required><input name='description' placeholder='Description' required><input name='category' placeholder='Category' required><select name='txn_type'><option value='income'>Income</option><option value='expense'>Expense</option></select><input name='amount' type='number' step='0.01' required><button>Add</button></form><table><tr><th>Date</th><th>Description</th><th>Category</th><th>Type</th><th>Amount</th></tr>{rows}</table></div>""")

@app.post("/transactions")
def add_tx(txn_date:str=Form(...),description:str=Form(...),category:str=Form(...),txn_type:str=Form(...),amount:Decimal=Form(...)):
    with engine.begin() as c: c.execute(text("INSERT INTO transactions(txn_date,description,category,txn_type,amount) VALUES(:d,:x,:c,:t,:a)"),{"d":txn_date,"x":description,"c":category,"t":txn_type,"a":amount})
    return RedirectResponse("/transactions",303)

@app.get("/customers",response_class=HTMLResponse)
def cust():
    with engine.connect() as c: items=c.execute(text("SELECT * FROM customers ORDER BY id DESC")).mappings().all()
    rows="".join(f"<tr><td>{r['name']}</td><td>{r['email'] or ''}</td><td>{r['phone'] or ''}</td></tr>" for r in items)
    return page("Customers",f"""<h1>Customers</h1><div class='card'><form method='post'><input name='name' placeholder='Name' required><input name='email' placeholder='Email'><input name='phone' placeholder='Phone'><button>Add</button></form><table><tr><th>Name</th><th>Email</th><th>Phone</th></tr>{rows}</table></div>""")

@app.post("/customers")
def add_c(name:str=Form(...),email:str=Form(""),phone:str=Form("")):
    with engine.begin() as c: c.execute(text("INSERT INTO customers(name,email,phone) VALUES(:n,:e,:p)"),{"n":name,"e":email,"p":phone})
    return RedirectResponse("/customers",303)

@app.get("/invoices",response_class=HTMLResponse)
def inv():
    with engine.connect() as c: items=c.execute(text("SELECT * FROM invoices ORDER BY id DESC")).mappings().all()
    rows="".join(f"<tr><td>INV-{r['id']:04d}</td><td>{r['customer_name']}</td><td>{r['issue_date']}</td><td>{r['due_date']}</td><td>{r['status']}</td><td>{m(r['amount'])}</td></tr>" for r in items)
    return page("Invoices",f"""<h1>Invoices</h1><div class='card'><form method='post'><input name='customer_name' placeholder='Customer' required><input name='issue_date' type='date' required><input name='due_date' type='date' required><select name='status'><option>Unpaid</option><option>Paid</option></select><input name='amount' type='number' step='0.01' required><button>Create</button></form><table><tr><th>Invoice</th><th>Customer</th><th>Issue</th><th>Due</th><th>Status</th><th>Amount</th></tr>{rows}</table></div>""")

@app.post("/invoices")
def add_i(customer_name:str=Form(...),issue_date:str=Form(...),due_date:str=Form(...),status:str=Form(...),amount:Decimal=Form(...)):
    with engine.begin() as c: c.execute(text("INSERT INTO invoices(customer_name,issue_date,due_date,status,amount) VALUES(:c,:i,:d,:s,:a)"),{"c":customer_name,"i":issue_date,"d":due_date,"s":status,"a":amount})
    return RedirectResponse("/invoices",303)
