"""Itemized sales workflow. Totals are calculated server-side with decimal money."""
import csv
import json
import secrets
from datetime import date
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from html import escape
from io import StringIO

from fastapi import Request, HTTPException
from fastapi.responses import HTMLResponse, RedirectResponse, StreamingResponse
from sqlalchemy import text

CENT = Decimal('0.01')


def dec(value, minimum=Decimal('0'), maximum=Decimal('100000000')):
    try:
        result = Decimal(str(value))
        if not result.is_finite() or not minimum <= result <= maximum:
            raise ValueError()
        return result
    except (InvalidOperation, ValueError, TypeError):
        raise HTTPException(400, 'Invalid numeric value.')


def cents(value):
    return value.quantize(CENT, rounding=ROUND_HALF_UP)


def clean(value, limit=500):
    value = str(value).strip()
    if not value or len(value) > limit:
        raise HTTPException(400, 'A required field is missing or too long.')
    return value


def calendar(value):
    try:
        return date.fromisoformat(str(value)).isoformat()
    except ValueError:
        raise HTTPException(400, 'Invalid date.')


def calculate(lines):
    if not isinstance(lines, list) or not 1 <= len(lines) <= 100:
        raise HTTPException(400, 'Enter between 1 and 100 items.')
    items = []
    for row in lines:
        if not isinstance(row, dict):
            raise HTTPException(400, 'Invalid item.')
        quantity = dec(row.get('quantity'), Decimal('0.001'), Decimal('100000'))
        if quantity != quantity.quantize(Decimal('0.001')):
            raise HTTPException(400, 'Quantity supports up to three decimal places.')
        price = cents(dec(row.get('price'), maximum=Decimal('1000000')))
        discount_rate = dec(row.get('discount', 0), maximum=Decimal('100'))
        tax_rate = dec(row.get('tax_rate', 0), maximum=Decimal('100'))
        gross = cents(quantity * price)
        discount = cents(gross * discount_rate / 100)
        subtotal = gross - discount
        tax = cents(subtotal * tax_rate / 100)
        items.append(dict(code=str(row.get('code', ''))[:80], description=clean(row.get('description', '')),
                          unit=clean(row.get('unit', 'pcs'), 30), quantity=str(quantity), price=str(price),
                          discount_rate=str(discount_rate), tax_rate=str(tax_rate),
                          discount=str(discount), subtotal=str(subtotal), tax=str(tax), total=str(subtotal+tax)))
    totals = {key: sum((Decimal(item[key]) for item in items), Decimal(0))
              for key in ('discount', 'subtotal', 'tax', 'total')}
    if totals['total'] > Decimal('100000000'):
        raise HTTPException(400, 'Document total is too large.')
    return items, totals


def init_sales(engine, pg):
    identity = 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' if pg else 'INTEGER PRIMARY KEY AUTOINCREMENT'
    with engine.begin() as conn:
        conn.execute(text(f'''CREATE TABLE IF NOT EXISTS sales_documents (
            id {identity}, document_no TEXT UNIQUE NOT NULL, kind TEXT NOT NULL,
            customer_id INTEGER NOT NULL, customer_name TEXT NOT NULL, document_date TEXT NOT NULL,
            due_date TEXT NOT NULL, terms TEXT NOT NULL, currency TEXT NOT NULL,
            items_json TEXT NOT NULL, subtotal NUMERIC NOT NULL, tax NUMERIC NOT NULL,
            total NUMERIC NOT NULL, discount NUMERIC NOT NULL, notes TEXT NOT NULL,
            invoice_id INTEGER, source_id INTEGER, converted_id INTEGER, created_by TEXT NOT NULL)'''))
        conn.execute(text(f'''CREATE TABLE IF NOT EXISTS sales_payments (
            id {identity}, document_id INTEGER NOT NULL, payment_date TEXT NOT NULL,
            amount NUMERIC NOT NULL, method TEXT NOT NULL, reference TEXT NOT NULL)'''))
        conn.execute(text('CREATE INDEX IF NOT EXISTS sales_source_idx ON sales_documents(source_id)'))


STYLE = '''<style>
.sales-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:22px}.sales-tabs a{padding:10px 15px;border:1px solid var(--line);border-radius:8px;text-decoration:none;color:var(--text)}.sales-tabs a.active{background:var(--goldsoft);color:var(--gold);border-color:var(--gold)}
.sales-banner{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:22px}.sales-banner h2{font-size:29px;margin:0 0 10px}.sales-actions{display:flex;gap:8px;flex-wrap:wrap}.sales-actions a{white-space:nowrap}.sales-table{overflow:auto}.sales-table input{width:100%;min-width:85px}.sales-table td{padding:8px}.sales-table .description{min-width:200px}.sales-label{display:grid;gap:7px;color:var(--muted);font-size:12px}.sales-summary{display:flex;gap:18px;justify-content:flex-end;align-items:center;flex-wrap:wrap;margin:20px 0;padding:18px;border:1px solid var(--line);border-radius:10px;background:var(--goldsoft)}.sales-summary strong{font-size:24px;color:var(--gold)}.sales-note{line-height:1.7;color:var(--muted)}.sales-id{color:var(--gold);text-decoration:none;font-weight:700}.sales-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.sales-stats .card{padding:18px}.sales-stats strong{display:block;font-size:24px;margin-top:10px}.sales-paper{max-width:1000px;margin:auto}.sales-heading{display:flex;justify-content:space-between;gap:20px;margin-bottom:24px}.sales-heading h2{margin:0 0 10px}.sales-heading p{margin:4px 0}.sales-error{padding:13px;color:#ff9198;background:#2b1114;border-radius:8px;margin-bottom:14px}.mobile-sales{display:none}
@media(max-width:900px){.sales-stats{grid-template-columns:repeat(2,1fr)}.sales-banner{align-items:flex-start;flex-direction:column}}
@media(max-width:780px){.mobile-sales{display:flex;padding:8px 14px;overflow:auto;gap:14px;border-bottom:1px solid var(--line)}.mobile-sales a{white-space:nowrap;color:var(--gold);text-decoration:none}.sales-heading{flex-direction:column}}
@media print{header,aside,.top,.sales-tabs,.no-print,.mobile-sales{display:none!important}.layout{display:block!important}body,html{background:white!important;color:black!important}main{padding:0!important}.card{background:white!important;border:0!important;box-shadow:none!important;color:black!important}td,th,h2,h3,p,strong{color:black!important}table{min-width:0!important}.sales-summary{background:white!important}.sales-paper{max-width:none}.sales-table{overflow:visible}}
</style>'''


def register_sales(app, ctx):
    engine, q, page, guard, editor_guard, user, setting, audit = [ctx[name] for name in
        ('engine', 'q', 'page', 'guard', 'editor_guard', 'user', 'setting', 'audit')]

    def amount(v, currency=None):
        return escape(currency or setting('currency', 'AED')) + ' ' + f'{Decimal(str(v or 0)):,.2f}'

    def ui(request, title, body, tab='overview'):
        links = [('overview', '/sales', 'Sales overview'), ('new', '/sales/new', 'New document'),
                 ('reports', '/sales/reports', 'Sales reports'), ('statements', '/sales/statements', 'Customer statements')]
        tabs = ''.join(f"<a class='{'active' if key==tab else ''}' href='{url}'>{label}</a>" for key,url,label in links)
        flash = request.session.pop('sales_flash', '')
        notice = f"<div class='flash'>{escape(flash)}</div>" if flash else ''
        return page(request, title, STYLE + f"<div class='sales-tabs'>{tabs}</div>" + notice + body)

    def get_doc(doc_id, conn=None, lock=False):
        sql = 'SELECT * FROM sales_documents WHERE id=:id'
        if lock and ctx['is_pg']():
            sql += ' FOR UPDATE'
        row = conn.execute(text(sql), {'id':doc_id}).mappings().first() if conn else q(sql, {'id':doc_id}, True)
        if not row:
            raise HTTPException(404, 'Document not found.')
        return row

    def insert_document(conn, payload):
        cols = ','.join(payload)
        vals = ','.join(':'+key for key in payload)
        return conn.execute(text(f'INSERT INTO sales_documents ({cols}) VALUES ({vals}) RETURNING id'), payload).scalar_one()

    def post_invoice(conn, payload, paid):
        total = Decimal(str(payload['total']))
        status = 'Paid' if paid >= total else ('Partially Paid' if paid > 0 else 'Unpaid')
        inv_id = conn.execute(text('''INSERT INTO invoices(invoice_no,customer_name,issue_date,due_date,status,subtotal,tax,total,paid,notes)
            VALUES(:document_no,:customer_name,:document_date,:due_date,:status,:subtotal,:tax,:total,:paid,:notes) RETURNING id'''),
            dict(payload, paid=str(paid), status=status)).scalar_one()
        conn.execute(text('''INSERT INTO transactions(txn_date,description,category,txn_type,amount,tax,reference,account_code)
            VALUES(:document_date,:description,'Sales','income',:subtotal,:tax,:document_no,'4000')'''),
            dict(payload,description='Sales invoice '+payload['document_no']))
        return inv_id

    def payment(conn, document_id, paid, when, method, reference=''):
        if paid:
            conn.execute(text('''INSERT INTO sales_payments(document_id,payment_date,amount,method,reference)
                VALUES(:doc,:date,:amount,:method,:reference)'''),
                {'doc':document_id,'date':when,'amount':str(paid),'method':method,'reference':reference})

    def listing(rows):
        body = ''
        for r in rows:
            body += f"<tr><td><a class='sales-id' href='/sales/{r['id']}'>{escape(r['document_no'])}</a></td><td>{r['kind']}</td><td>{escape(r['customer_name'])}</td><td>{r['document_date']}</td><td>{r['terms']}</td><td>{amount(r['total'],r['currency'])}</td><td>{'Converted' if r['converted_id'] else 'Saved'}</td><td><a class='sales-id' href='/sales/{r['id']}'>View</a></td></tr>"
        return "<div class='sales-table'><table><tr><th>Document</th><th>Type</th><th>Customer</th><th>Date</th><th>Payment terms</th><th>Total</th><th>Status</th><th></th></tr>" + (body or "<tr><td colspan='8'>No documents yet</td></tr>") + '</table></div>'

    @app.get('/sales', response_class=HTMLResponse)
    def overview(request:Request):
        g=guard(request)
        if g:return g
        search=request.query_params.get('search','').strip()
        kind=request.query_params.get('kind','')
        params={'search':'%'+search+'%'}
        where='WHERE (LOWER(document_no) LIKE LOWER(:search) OR LOWER(customer_name) LIKE LOWER(:search))'
        if kind in ('Quotation','Sales Invoice','Credit Note'):
            where+=' AND kind=:kind';params['kind']=kind
        docs=q('SELECT * FROM sales_documents '+where+' ORDER BY id DESC LIMIT 200',params)
        stats=q("SELECT kind,COALESCE(SUM(total),0) total,COUNT(*) count FROM sales_documents GROUP BY kind")
        stats={r['kind']:r for r in stats}
        totals={k:Decimal(str(stats.get(k,{}).get('total',0))) for k in ('Quotation','Sales Invoice','Credit Note')}
        ar=q("SELECT COALESCE(SUM(total-paid),0) value FROM invoices",one=True)['value']
        cards=''.join(f"<div class='card'><span>{label}</span><strong>{value}</strong></div>" for label,value in [
            ('Quotations',stats.get('Quotation',{}).get('count',0)),('Net sales',amount(totals['Sales Invoice']-totals['Credit Note'])),
            ('Sales returns',amount(totals['Credit Note'])),('Receivables',amount(ar))])
        actions="<a class='btn' href='/sales/new?kind=Quotation'>New quotation</a><a class='btn' href='/sales/new?terms=Cash'>New cash sale</a><a class='btn' href='/sales/new?terms=Credit'>New credit sale</a>" if user(request)['role'] in ('Admin','Accountant') else ''
        filters=f"""<form class='gridform' method='get'><input name='search' value='{escape(search,quote=True)}' placeholder='Search'><select name='kind'><option value=''>All documents</option>{''.join(f"<option {'selected' if kind==k else ''}>{k}</option>" for k in ('Quotation','Sales Invoice','Credit Note'))}</select><button>Search</button></form>"""
        return ui(request,'Sales Workspace',f"<div class='sales-banner'><div><h2>Sales overview</h2><p class='sales-note'>Quotation to invoice, payment to return — one connected workflow.</p></div><div class='sales-actions'>{actions}</div></div><div class='sales-stats'>{cards}</div><div class='card'>{filters}{listing(docs)}</div>")

    @app.get('/sales/new', response_class=HTMLResponse)
    def new_document(request:Request):
        g=editor_guard(request)
        if g:return g
        kind=request.query_params.get('kind','Sales Invoice')
        terms=request.query_params.get('terms','Credit')
        customer_options=''.join(f"<option value='{r['id']}'>{escape(r['name'])}</option>" for r in q('SELECT id,name FROM customers ORDER BY name'))
        token=secrets.token_hex(16)
        request.session['sales_token']=token
        body=f"""<div class='card'><form id='sales-form' method='post' action='/sales/new'>
        <input type='hidden' name='token' value='{token}'><input type='hidden' name='lines' id='lines'>
        <div class='gridform' style='display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:14px;margin-bottom:24px'>
        <label class='sales-label'><span>Type</span><select name='kind'><option {'selected' if kind=='Quotation' else ''}>Quotation</option><option {'selected' if kind!='Quotation' else ''}>Sales Invoice</option></select></label>
        <label class='sales-label'><span>Customer</span><select name='customer_id' required><option value=''>Select customer</option>{customer_options}</select></label>
        <label class='sales-label'><span>Document date</span><input type='date' name='document_date' value='{date.today()}' required></label>
        <label class='sales-label'><span>Due date</span><input type='date' name='due_date' value='{date.today()}' required></label>
        <label class='sales-label'><span>Payment terms</span><select name='terms'><option {'selected' if terms=='Cash' else ''}>Cash</option><option {'selected' if terms!='Cash' else ''}>Credit</option></select></label>
        <label class='sales-label'><span>Payment amount</span><input name='paid' type='number' step='.01' min='0' value='0'></label></div>
        <div class='sales-table'><table id='item-editor'><thead><tr><th>Item code</th><th>Item description</th><th>Unit</th><th>Quantity</th><th>Unit price</th><th>Discount %</th><th>Tax %</th><th>Total</th><th></th></tr></thead><tbody></tbody></table></div>
        <p><button type='button' class='reset-btn' id='add-line'>Add line</button></p>
        <div class='sales-summary'><div><span>Subtotal</span><p id='preview-subtotal'>0.00</p></div><div><span>Discount</span><p id='preview-discount'>0.00</p></div><div><span>VAT</span><p id='preview-tax'>0.00</p></div><div><span>Total</span><p><strong id='preview-total'>0.00</strong></p></div></div>
        <label class='sales-label'><span>Notes</span><textarea name='notes' maxlength='2000' rows='2'></textarea></label><p><button>Save document</button></p></form></div>"""
        script=EDITOR_SCRIPT.replace('__VAT__',str(dec(setting('vat_rate','5'),maximum=Decimal(100))))
        return ui(request,'New document',body+script,'new')

    @app.post('/sales/new')
    async def create_document(request:Request):
        g=editor_guard(request)
        if g:return g
        form=await request.form()
        if not form.get('token') or not secrets.compare_digest(str(form['token']),request.session.get('sales_token','')):
            raise HTTPException(400,'This form has already been submitted or expired. Open a new document.')
        kind=form.get('kind');terms=form.get('terms')
        if kind not in ('Quotation','Sales Invoice') or terms not in ('Cash','Credit'):
            raise HTTPException(400,'Invalid document type or terms.')
        try:
            items,totals=calculate(json.loads(form.get('lines','')))
            customer_id=int(form.get('customer_id',''))
        except (ValueError,TypeError):
            raise HTTPException(400,'Invalid customer or item data.')
        customer=q('SELECT * FROM customers WHERE id=:id',{'id':customer_id},True)
        if not customer:raise HTTPException(400,'Select an existing customer.')
        when=calendar(form.get('document_date'));due=calendar(form.get('due_date'))
        if due<when:raise HTTPException(400,'Due date must not be before document date.')
        paid=cents(dec(form.get('paid',0)))
        if kind=='Quotation':paid=Decimal(0)
        elif terms=='Cash':paid=totals['total']
        if paid>totals['total']:raise HTTPException(400,'Payment cannot exceed document total.')
        prefix='QT' if kind=='Quotation' else 'SI'
        payload=dict(document_no=prefix+'-'+date.today().strftime('%y%m%d')+'-'+secrets.token_hex(3).upper(),
                     kind=kind,customer_id=customer_id,customer_name=customer['name'],document_date=when,due_date=due,
                     terms=terms,currency=setting('currency','AED'),items_json=json.dumps(items,ensure_ascii=False),
                     **{k:str(v) for k,v in totals.items()},notes=str(form.get('notes',''))[:2000],
                     invoice_id=None,source_id=None,converted_id=None,created_by=user(request)['username'])
        with engine.begin() as conn:
            if kind=='Sales Invoice':payload['invoice_id']=post_invoice(conn,payload,paid)
            doc_id=insert_document(conn,payload)
            payment(conn,doc_id,paid,when,'Cash' if terms=='Cash' else 'Bank Transfer')
        request.session.pop('sales_token',None)
        audit(request,'CREATE_SALES_DOCUMENT','Sales',payload['document_no'],kind)
        return RedirectResponse(f'/sales/{doc_id}',303)

    @app.get('/sales/reports',response_class=HTMLResponse)
    def sales_reports(request:Request):
        g=guard(request)
        if g:return g
        start=request.query_params.get('from','');end=request.query_params.get('to','')
        conditions=["kind!='Quotation'"];params={}
        if start:conditions.append('document_date>=:start');params['start']=calendar(start)
        if end:conditions.append('document_date<=:end');params['end']=calendar(end)
        if start and end and start>end:raise HTTPException(400,'Invalid date range.')
        rows=q('SELECT * FROM sales_documents WHERE '+' AND '.join(conditions)+' ORDER BY document_date DESC,id DESC',params)
        if request.query_params.get('format')=='csv':
            out=StringIO();writer=csv.writer(out);writer.writerow(['Document','Type','Customer','Date','Currency','Subtotal','Tax','Total'])
            for r in rows:
                def safe(v):
                    s=str(v);return "'"+s if s[:1] in ('=','+','-','@','\t','\r') else s
                writer.writerow([safe(r[k]) for k in ('document_no','kind','customer_name','document_date','currency','subtotal','tax','total')])
            return StreamingResponse(iter(['\ufeff'+out.getvalue()]),media_type='text/csv',headers={'Content-Disposition':'attachment; filename=sales-report.csv'})
        total=sum((Decimal(str(r['subtotal']))*(1 if r['kind']=='Sales Invoice' else -1) for r in rows),Decimal(0))
        tax=sum((Decimal(str(r['tax']))*(1 if r['kind']=='Sales Invoice' else -1) for r in rows),Decimal(0))
        from urllib.parse import urlencode
        export='/sales/reports?'+urlencode({'from':start,'to':end,'format':'csv'})
        body=f"<div class='card'><p class='muted'>Sales documents only</p><form class='gridform'><label class='sales-label'><span>From</span><input type='date' name='from' value='{escape(start)}'></label><label class='sales-label'><span>To</span><input type='date' name='to' value='{escape(end)}'></label><button>Apply filters</button><a class='btn' href='{escape(export,quote=True)}'>Export CSV</a></form><div class='sales-summary'><span>Sales before tax</span><strong>{amount(total)}</strong><span>VAT</span><strong>{amount(tax)}</strong><span>Net sales</span><strong>{amount(total+tax)}</strong></div>{listing(rows)}</div>"
        return ui(request,'Sales reports',body,'reports')

    @app.get('/sales/statements',response_class=HTMLResponse)
    def statements(request:Request):
        g=guard(request)
        if g:return g
        customer_id=request.query_params.get('customer_id','')
        customers=q('SELECT id,name FROM customers ORDER BY name')
        options=''.join(f"<option value='{r['id']}' {'selected' if str(r['id'])==customer_id else ''}>{escape(r['name'])}</option>" for r in customers)
        body=f"<div class='card'><form class='gridform'><select name='customer_id' required><option value=''>Select customer</option>{options}</select><button>View</button></form>"
        selected=next((r for r in customers if str(r['id'])==customer_id),None)
        if selected:
            invoices=q('SELECT * FROM invoices WHERE customer_name=:name ORDER BY issue_date,id',{'name':selected['name']})
            balance=sum((Decimal(str(r['total']))-Decimal(str(r['paid'])) for r in invoices),Decimal(0))
            rows=''.join(f"<tr><td>{escape(r['invoice_no'])}</td><td>{r['issue_date']}</td><td>{r['due_date']}</td><td>{amount(r['total'])}</td><td>{amount(r['paid'])}</td><td>{amount(Decimal(str(r['total']))-Decimal(str(r['paid'])))}</td></tr>" for r in invoices)
            body+=f"<h2>{escape(selected['name'])}</h2><p>All customer invoices</p><div class='sales-summary'><span>Customer balance</span><strong>{amount(balance)}</strong></div><div class='sales-table'><table><tr><th>Invoice</th><th>Date</th><th>Due</th><th>Net amount after returns</th><th>Received</th><th>Balance</th></tr>{rows}</table></div>"
        else:body+='<p class="muted">No customer selected</p>'
        return ui(request,'Customer statements',body+'</div>','statements')

    @app.get('/sales/{doc_id}',response_class=HTMLResponse)
    def document_detail(request:Request,doc_id:int):
        g=guard(request)
        if g:return g
        doc=get_doc(doc_id);items=json.loads(doc['items_json']);currency=doc['currency']
        rows=''.join(f"<tr><td>{escape(r['code'])}</td><td>{escape(r['description'])}</td><td>{escape(r['unit'])}</td><td>{r['quantity']}</td><td>{amount(r['price'],currency)}</td><td>{amount(r['discount'],currency)}</td><td>{amount(r['tax'],currency)}</td><td>{amount(r['total'],currency)}</td></tr>" for r in items)
        body=f"""<div class='card sales-paper'><div class='sales-heading'><div><p class='eyebrow'>{escape(setting('company_name','Accountant Pro'))}</p><h2>{doc['kind']}</h2><p>{escape(doc['document_no'])}</p></div><div><p><b>{escape(doc['customer_name'])}</b></p><p>{doc['document_date']} · {doc['terms']}</p><p><span>Due date</span>: {doc['due_date']}</p></div></div><div class='sales-table'><table><tr><th>Item code</th><th>Item description</th><th>Unit</th><th>Quantity</th><th>Unit price</th><th>Discount</th><th>VAT</th><th>Total</th></tr>{rows}</table></div><div class='sales-summary'><span>Subtotal</span><b>{amount(doc['subtotal'],currency)}</b><span>VAT</span><b>{amount(doc['tax'],currency)}</b><span>Total</span><strong>{amount(doc['total'],currency)}</strong></div><p class='sales-note'>{escape(doc['notes'])}</p><div class='no-print sales-actions'><button type='button' onclick='window.print()'>Print / Save PDF</button></div>"""
        can_edit=user(request)['role'] in ('Admin','Accountant')
        token=secrets.token_hex(16);request.session['sales_action_token']=token
        csrf=f"<input type='hidden' name='token' value='{token}'>"
        if doc['kind']=='Quotation':
            if doc['converted_id']:body+=f"<p><a class='sales-id' href='/sales/{doc['converted_id']}'>Linked invoice</a></p>"
            elif can_edit:body+=f"<form class='gridform no-print' method='post' action='/sales/{doc_id}/convert'>{csrf}<button>Convert to invoice</button></form>"
        if doc['source_id']:body+=f"<p><a class='sales-id' href='/sales/{doc['source_id']}'>Original invoice</a></p>"
        if doc['kind']=='Sales Invoice':
            inv=q('SELECT * FROM invoices WHERE id=:id',{'id':doc['invoice_id']},True)
            balance=Decimal(str(inv['total']))-Decimal(str(inv['paid']))
            body+=f"<div class='sales-summary'><span>Net amount after returns</span><b>{amount(inv['total'],currency)}</b><span>Received</span><b>{amount(inv['paid'],currency)}</b><span>Balance</span><strong>{amount(balance,currency)}</strong></div>"
            pays=q('SELECT * FROM sales_payments WHERE document_id=:id ORDER BY id',{'id':doc_id})
            body+='<h3>Payments</h3>'+''.join(f"<p>{r['payment_date']} · {escape(r['method'])} · {amount(r['amount'],currency)} · {escape(r['reference'])}</p>" for r in pays)
            for r in pays:
                if r['method']=='Refund pending' and can_edit:
                    body+=f"<form class='gridform no-print' method='post' action='/sales/{doc_id}/refund/{r['id']}'>{csrf}<p><span>Refund pending</span>: {amount(-Decimal(str(r['amount'])),currency)}</p><button>Confirm refund paid</button></form>"
            if can_edit and balance>0:body+=f"<form class='gridform no-print' method='post' action='/sales/{doc_id}/payment'>{csrf}<input type='number' name='amount' min='.01' max='{balance}' step='.01' placeholder='Payment amount' required><input name='payment_date' type='date' value='{date.today()}' required><select name='method'><option>Cash</option><option>Bank Transfer</option><option>Card</option></select><input name='reference' placeholder='Reference' maxlength='100'><button>Record payment</button></form>"
            returns=q("SELECT * FROM sales_documents WHERE source_id=:id AND kind='Credit Note'",{'id':doc_id})
            if returns:body+='<h3>Sales returns</h3>'+listing(returns)
            returned={}
            for credit in returns:
                for line in json.loads(credit['items_json']):
                    key=line['line_index'];returned[key]=returned.get(key,Decimal(0))+Decimal(line['quantity'])
            if can_edit:
                return_rows=''
                for index,line in enumerate(items):
                    remaining=Decimal(line['quantity'])-returned.get(index,Decimal(0))
                    return_rows+=f"<label class='sales-label'><span>{escape(line['description'])}</span><input type='number' name='return_{index}' min='0' max='{remaining}' step='.001' value='0'><span>Remaining quantity</span>: {remaining}</label>"
                body+=f"<div class='no-print'><h3>Sales return</h3><form class='gridform' method='post' action='/sales/{doc_id}/return'>{csrf}{return_rows}<input name='reason' placeholder='Return reason' maxlength='500' required><button>Save return</button></form></div>"
        return ui(request,doc['kind'],body+'</div>')

    async def action_form(request):
        form=await request.form()
        if not form.get('token') or not secrets.compare_digest(str(form['token']),request.session.get('sales_action_token','')):
            raise HTTPException(400,'This form has expired. Reload the document.')
        return form

    @app.post('/sales/{doc_id}/convert')
    async def convert(request:Request,doc_id:int):
        g=editor_guard(request)
        if g:return g
        await action_form(request)
        with engine.begin() as conn:
            doc=dict(get_doc(doc_id,conn,True))
            if doc['kind']!='Quotation':raise HTTPException(400,'Only quotations can be converted.')
            if doc['converted_id']:return RedirectResponse(f"/sales/{doc['converted_id']}",303)
            payload={k:v for k,v in doc.items() if k!='id'}
            payload.update(document_no='SI-'+secrets.token_hex(5).upper(),kind='Sales Invoice',source_id=doc_id,
                           document_date=str(date.today()),due_date=max(doc['due_date'],str(date.today())),converted_id=None,
                           created_by=user(request)['username'])
            paid=Decimal(str(payload['total'])) if payload['terms']=='Cash' else Decimal(0)
            payload['invoice_id']=post_invoice(conn,payload,paid)
            new_id=insert_document(conn,payload)
            payment(conn,new_id,paid,payload['document_date'],'Cash')
            conn.execute(text('UPDATE sales_documents SET converted_id=:new WHERE id=:id'),{'new':new_id,'id':doc_id})
        audit(request,'CONVERT_QUOTATION','Sales',doc['document_no'],payload['document_no'])
        return RedirectResponse(f'/sales/{new_id}',303)

    @app.post('/sales/{doc_id}/payment')
    async def record_payment(request:Request,doc_id:int):
        g=editor_guard(request)
        if g:return g
        form=await action_form(request);paid=cents(dec(form.get('amount'),Decimal('.01')))
        when=calendar(form.get('payment_date'));method=form.get('method')
        if method not in ('Cash','Bank Transfer','Card'):raise HTTPException(400,'Invalid payment method.')
        with engine.begin() as conn:
            doc=get_doc(doc_id,conn,True)
            if doc['kind']!='Sales Invoice':raise HTTPException(400,'Only invoices accept payments.')
            inv=conn.execute(text('SELECT * FROM invoices WHERE id=:id'),{'id':doc['invoice_id']}).mappings().one()
            if paid>Decimal(str(inv['total']))-Decimal(str(inv['paid'])):raise HTTPException(400,'Payment exceeds outstanding balance.')
            new_paid=Decimal(str(inv['paid']))+paid
            status='Paid' if new_paid==Decimal(str(inv['total'])) else 'Partially Paid'
            conn.execute(text('UPDATE invoices SET paid=:paid,status=:status WHERE id=:id'),{'paid':str(new_paid),'status':status,'id':doc['invoice_id']})
            payment(conn,doc_id,paid,when,method,str(form.get('reference',''))[:100])
        request.session.pop('sales_action_token',None)
        audit(request,'RECORD_SALES_PAYMENT','Sales',doc['document_no'],str(paid))
        return RedirectResponse(f'/sales/{doc_id}',303)

    @app.post('/sales/{doc_id}/return')
    async def sales_return(request:Request,doc_id:int):
        g=editor_guard(request)
        if g:return g
        form=await action_form(request);reason=clean(form.get('reason',''))
        with engine.begin() as conn:
            doc=dict(get_doc(doc_id,conn,True))
            if doc['kind']!='Sales Invoice':raise HTTPException(400,'Returns require an original sales invoice.')
            items=json.loads(doc['items_json'])
            credits=conn.execute(text("SELECT items_json FROM sales_documents WHERE source_id=:id AND kind='Credit Note'"),{'id':doc_id}).mappings().all()
            previous={}
            for credit in credits:
                for line in json.loads(credit['items_json']):
                    key=line['line_index']
                    if key not in previous:previous[key]={k:Decimal(0) for k in ('quantity','discount','subtotal','tax','total')}
                    for k in previous[key]:previous[key][k]+=Decimal(line[k])
            returned=[]
            for index,line in enumerate(items):
                quantity=dec(form.get(f'return_{index}',0),maximum=Decimal('100000'))
                if not quantity:continue
                if quantity!=quantity.quantize(Decimal('.001')):raise HTTPException(400,'Invalid quantity precision.')
                used=previous.get(index,{k:Decimal(0) for k in ('quantity','discount','subtotal','tax','total')})
                remaining=Decimal(line['quantity'])-used['quantity']
                if quantity>remaining:raise HTTPException(400,'Return exceeds remaining item quantity.')
                returned_line=dict(line,quantity=str(quantity),line_index=index)
                for key in ('discount','subtotal','tax'):
                    # Cumulative rounding guarantees partial returns never exceed original money.
                    target=cents(Decimal(line[key])*(used['quantity']+quantity)/Decimal(line['quantity']))
                    returned_line[key]=str(target-used[key])
                returned_line['total']=str(Decimal(returned_line['subtotal'])+Decimal(returned_line['tax']))
                returned.append(returned_line)
            if not returned:raise HTTPException(400,'Enter at least one return quantity.')
            totals={key:sum((Decimal(line[key]) for line in returned),Decimal(0)) for key in ('discount','subtotal','tax','total')}
            payload={k:v for k,v in doc.items() if k!='id'}
            payload.update(document_no='CN-'+secrets.token_hex(5).upper(),kind='Credit Note',source_id=doc_id,converted_id=None,
                           document_date=str(date.today()),items_json=json.dumps(returned,ensure_ascii=False),notes=reason,
                           **{k:str(v) for k,v in totals.items()},created_by=user(request)['username'])
            credit_id=insert_document(conn,payload)
            inv=conn.execute(text('SELECT * FROM invoices WHERE id=:id'),{'id':doc['invoice_id']}).mappings().one()
            net=cents(Decimal(str(inv['total']))-totals['total'])
            refund=max(Decimal(str(inv['paid']))-net,Decimal(0));paid=min(Decimal(str(inv['paid'])),net)
            status='Paid' if paid==net else ('Partially Paid' if paid else 'Unpaid')
            conn.execute(text('''UPDATE invoices SET total=:total,subtotal=:sub,tax=:tax,paid=:paid,status=:status WHERE id=:id'''),
                {'total':str(net),'sub':str(Decimal(str(inv['subtotal']))-totals['subtotal']),
                 'tax':str(Decimal(str(inv['tax']))-totals['tax']),'paid':str(paid),'status':status,'id':doc['invoice_id']})
            conn.execute(text('''INSERT INTO transactions(txn_date,description,category,txn_type,amount,tax,reference,account_code)
                VALUES(:date,:description,'Sales return','income',:amount,:tax,:ref,'4000')'''),
                {'date':str(date.today()),'description':'Sales return '+payload['document_no'],
                 'amount':str(-totals['subtotal']),'tax':str(-totals['tax']),'ref':payload['document_no']})
            payment(conn,doc_id,-refund,str(date.today()),'Refund pending',payload['document_no'])
        request.session.pop('sales_action_token',None)
        audit(request,'CREATE_SALES_RETURN','Sales',payload['document_no'],doc['document_no'])
        return RedirectResponse(f'/sales/{credit_id}',303)

    @app.post('/sales/{doc_id}/refund/{payment_id}')
    async def confirm_refund(request:Request,doc_id:int,payment_id:int):
        g=editor_guard(request)
        if g:return g
        await action_form(request)
        with engine.begin() as conn:
            doc=get_doc(doc_id,conn,True)
            result=conn.execute(text("UPDATE sales_payments SET method='Refund',payment_date=:date WHERE id=:id AND document_id=:doc AND method='Refund pending'"),
                {'id':payment_id,'doc':doc_id,'date':str(date.today())})
            if not result.rowcount:raise HTTPException(400,'Refund is not pending for this invoice.')
        request.session.pop('sales_action_token',None)
        audit(request,'CONFIRM_SALES_REFUND','Sales',doc['document_no'],str(payment_id))
        return RedirectResponse(f'/sales/{doc_id}',303)


EDITOR_SCRIPT = '''<script>
const editor=document.querySelector('#item-editor tbody');
function updateTotals(){
  let subtotal=0,tax=0,discount=0;
  editor.querySelectorAll('tr').forEach(row=>{
    const val=name=>Number(row.querySelector('[data-field="'+name+'"]').value)||0;
    const gross=Math.round(val('quantity')*val('price')*100)/100;
    const d=Math.round(gross*val('discount'))/100;
    const sub=gross-d,t=Math.round(sub*val('tax_rate'))/100;
    subtotal+=sub;tax+=t;discount+=d;row.querySelector('.line-total').textContent=(sub+t).toFixed(2);
  });
  document.querySelector('#preview-subtotal').textContent=subtotal.toFixed(2);
  document.querySelector('#preview-tax').textContent=tax.toFixed(2);
  document.querySelector('#preview-discount').textContent=discount.toFixed(2);
  document.querySelector('#preview-total').textContent=(subtotal+tax).toFixed(2);
}
function addLine(){
  const row=document.createElement('tr');
  row.innerHTML=`<td><input data-field="code" maxlength="80" aria-label="Item code"></td><td><input class="description" data-field="description" maxlength="500" aria-label="Item description" required></td><td><input data-field="unit" value="pcs" maxlength="30" aria-label="Unit" required></td><td><input data-field="quantity" type="number" value="1" min=".001" max="100000" step=".001" aria-label="Quantity" required></td><td><input data-field="price" type="number" min="0" max="1000000" step=".01" value="0" aria-label="Unit price" required></td><td><input data-field="discount" type="number" value="0" min="0" max="100" step=".01" aria-label="Discount percent" required></td><td><input data-field="tax_rate" type="number" value="__VAT__" min="0" max="100" step=".01" aria-label="Tax percent" required></td><td class="line-total">0.00</td><td><button type="button" class="reset-btn">Remove</button></td>`;
  row.querySelector('button').onclick=()=>{if(editor.children.length>1){row.remove();updateTotals();}};
  row.addEventListener('input',updateTotals);editor.append(row);
  if(typeof applyLanguage==='function')applyLanguage(localStorage.getItem('accountant_lang')||'en');
}
document.querySelector('#add-line').onclick=()=>{if(editor.children.length<100)addLine();};
document.querySelector('#sales-form').addEventListener('submit',()=>{
  const lines=[...editor.querySelectorAll('tr')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-field]')].map(el=>[el.dataset.field,el.value])));
  document.querySelector('#lines').value=JSON.stringify(lines);
});
addLine();
</script>'''
